### PR TITLE
Decrease blocking humidity delay

### PR DESCRIPTION
**Pull request by nseidle**
This PR

* Reduces humidity blocking conversion time to match datasheet
* Remove Wire.begin from .begin() (best practice)
* Add Wire.h to .h for the instances where user includes this lib before Wire.h 
* Increase examples to 115200bps (best practice)

### CODE REVIEW

**Comment by nseidle** [comment]
There's a lot of whitespace changes. I recommend you look at the commits individually.

**Review by PaulZC — APPROVED** [review]

**Review by PaulZC — APPROVED** [review]
OK - thank you

**Review by PaulZC — APPROVED** [review]
OK - nice one - thank you

**Review by PaulZC — APPROVED** [review]
Wow - great catch! Thank you!
I wonder if this helps explain why the sensor doesn't always .begin cleanly first time?

**Review by PaulZC — APPROVED** [review]
Woah. I hope these changes are automated? (Otherwise that was a _lot_ of typing!)
Thanks!

**Comment by PaulZC** [comment]
Hi Nathan (@nseidle),
I'm seeing this fail on both the Artemis ATP and the Global Tracker... (It works OK on the RedBoard Qwiic ATmega328 though.)
It begins OK but then fails on the first read, part way through the first Serial.print. Here's the output from Example8 when running on the ATP:
```
Qwiic PHT Sensor MS8607 Example
Te
```
("Te" are the first two letters of "Temperature")
But it must be working on the OLA?
I shall investigate!
Thanks,
Paul

**Comment by PaulZC** [comment]
OK. I think I've found it...
If I revert [Owen's latest commit](https://github.com/PaulZC/Arduino_Apollo3/commit/f09f3856b1713bf6d3295c0b20cba110eec7f01f) everything starts working again...
Here's the output from Example8_Artemis_Pressure when running on the ATP with runtime.tools.arm-none-eabi-gcc-8-2018-q4-major.path
```
Qwiic PHT Sensor MS8607 Example
Temperature=19.8(C) Pressure=1009.300(hPa or mbar)
Temperature=19.8(C) Pressure=1009.340(hPa or mbar)
Temperature=19.8(C) Pressure=1009.330(hPa or mbar)
Temperature=19.8(C) Pressure=1009.300(hPa or mbar)
Temperature=19.8(C) Pressure=1009.300(hPa or mbar)
```
If I include the latest commit and use runtime.tools.arm-none-eabi-gcc-7-2017q4.path I get this:
```
Qwiic PHT Sensor MS8607 Example
Te
```
I'll raise an issue in the Arduino_Apollo3 repo.
Cheers,
Paul

**Comment by oclyke** [comment]
I'm curious if these are actually I2C issues or rather Serial printing issues. Nate and I have already observed issues with float format printing when using 2017-q4. Have you confirmed that there are I2C errors?

**Comment by PaulZC** [comment]
Thanks Owen (@oclyke),
Nathan mentioned the float print problem during our call. Yes, it is definitely that - nothing to do with I2C errors! And the really weird thing is that it doesn't seem to be limited to actually printing the float. I'm seeing the code freeze when trying to calculate a float/double too.
All the best,
Paul

**Pull request merged**
